### ISSUE TITLE
PNG screenshot

### ISSUE THREAD

**Issue by lmaderer** [AlbertoPdRF/root-file-viewer#13]
Hi, I see that there is a camera icon "Create PNG" while looking e.g. at a histogram, but where are these saved?
Thanks, Lukas

**Comment by AlbertoPdRF** [comment]
Hey @lmaderer!

I've been investigating, and the PNGs don't get saved anywhere because VS Code does not allow for downloads from within WebViews, which is how [`JSROOT` implements the `saveAs` method](https://github.com/root-project/jsroot/blob/master/modules/gpad/RPadPainter.mjs#L1198-L1216). I don't know if there's an easy way to work around this, but I'm adding @linev to the conversation just in case.

**Comment by linev** [comment]
Hi,

For the moment JSROOT uses loose `<a>` element inside HTML page to start save image dialog - this is standard method for web browsers. Probably, in case of `WebView` one can transport file content into **Code** context and then store as normal file on file system.
I could provide hook in the JSROOT to implement such function - if this makes sense.

**Comment by AlbertoPdRF** [comment]
That would be great!

**Comment by AlbertoPdRF** [comment]
This has been addressed in 48e321b91d363b6a94551c5d4bb5354775654a6e, and will be included in a release soon :shipit:
